image: kkarczmarczyk/node-yarn:8.0

variables:
  GIT_SSL_NO_VERIFY: "true"

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh

test:
  stage: test
  script:
    - yarn --version
    - node --version
    - yarn install-all
    - yarn test
  artifacts:
    paths:
      - coverage
    expire_in: 30 days

deploy:
  stage: deploy
  script:
    - git remote add -f target ssh://git@heroku.com/gccgame.git
    - git config user.name "Ryo Wheatley - Deploy"
    - git config user.email "ryo.capricorn92@gmail.com"
    - git checkout master
    - git push target master
  environment:
    name: production
    url: https://gccgame.herokuapp.com/
  only:
    - master
